zone:
  world: world
  center:
    x: 0.0
    z: 0.0
  radius: 100.0

shards-per-minute: 1

# %player% = player name, %amount% = amount
shard-command: "shardmanager add %player% %amount%"

messages:
  received: "&d+%amount% Gems"
  actionbar-in-zone: "&d\u2764 Gem Zone &7| &fNext gem in &d%seconds%s"
  actionbar-out-zone: ""
  afk: "&7Teleporting to AFK area..."
  blocked-command: "&cUnknown command."

# Format: x,y,z,yaw,pitch,world
afk-location: "0.5,0.0,0.5,0.0,0.0,spawn"
blocked-commands:
  - /pl
  - /plugins
  - /ver
  - /version
  - /bukkit:plugins
  - /bukkit:about
# Aktiviert zusätzliche Konsolenausgaben für das Debugging
debug: true

# Die Liste der verbotenen Modifikationen, die per Übersetzungsschlüssel (Translation-Key) geprüft werden
disallowed-mods:
  meteor:
    translation-key: "key.meteor-client.open-gui"
    fallback: "normal"
  freecam:
    translation-key: "key.freecam.toggle"
    fallback: "normal"
  # Hier kannst du in Zukunft weitere Mods eintragen:
  # anderedemo:
  #   translation-key: "key.andere-mod.test"
  #   fallback: "standard"

# Was soll passieren, wenn ein Mod oder ein Timeout (Bypass-Versuch) erkannt wird?
action:
  # Mögliche Typen: "kick" oder "command"
  type: "command"

  # Die Zeilen, die dem Spieler angezeigt werden (bei "kick")
  # oder die Befehle, die die Konsole ausführt (bei "command")
  #
  # Platzhalter:
  # %player% - Der Name des Spielers
  # %mod%    - Der Name des erkannten Mods (z.B. "Meteor Client" oder "Timeout")
  content: "ban %player% 10s &cDu wurdest gebannt! Grund:  Unerlaubte Clientmodifikation (%mod%)."

